apiVersion: apps/v1
kind: Deployment
metadata:
  name: react_app
spec:
 replicas: 1
 selector:
   matchLabels:
       name: react_app
 template:
   metadata:
     name: react_app-pod
     labels:
       name: react_app
   spec:
      containers:
         - name: react_app-pod
           image: 10.83.0.202:9082/docker-hub-virtual/canadalabs/reactapp:${BUILD_NUMBER}
