apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: default
spec:
  ports:
  - nodePort: 30994
    port: 9006
    protocol: TCP
    targetPort: 9005
  selector:
    name: ${APP_NAME}
  type: NodePort