apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 9112
  selector:
    name: ${APP_NAME}
  type: NodePort