apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: default
spec:
  ports:
  - nodePort: 30992
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    name: pet
  type: NodePort
